version: "3.3"

services:
  hummingqueue:
    image: "traefik:v2.8"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mongo:
    image: "mongo:5.0"
    restart: "unless-stopped"
    environment:
     - "MONGO_INITDB_ROOT_USERNAME=root"
     - "MONGO_INITDB_ROOT_PASSWORD=pass"

  api:
    build:
      context: "api"
    ports:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`api.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

