[server]
baseurl = "nablachem.org"

[datacenter]
redis_host = "141.51.205.42"
redis_port = "42424"
name = "Kassel"
partitions = "AG-CompChem,public,public2,public4,public2023"
envs = "/home/groups/nablachem/hmq/envs"
binaries = "/home/groups/nablachem/hmq/bin"
tmpdir = "/home/groups/nablachem/hmq/tmp"
maxjobs = 20
