[server]
baseurl = "nablachem.org"
redis_host = "141.51.205.42"
redis_port = "42424"

[datacenter]
name = "Kassel"
envs = "/home/groups/nablachem/hmq/envs"
binaries = "/home/groups/nablachem/hmq/bin"
tmpdir = "/home/groups/nablachem/hmq/tmp"
maxjobs = 20
