version: "3.3"

services:
  hummingqueue:
    image: "traefik:v2.8"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mongo:
    image: "mongo:5.0"
    restart: "unless-stopped"
    ports:
     - "27017:27017"
    environment:
     - "MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}"
     - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}"

  minio:
    image: "minio/minio:RELEASE.2022-01-08T03-11-54Z"
    restart: "unless-stopped"
    command: "server /data --console-address :9001 --address :9000"
    expose:
      - 9000
      - 9001
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASS}"
      - "MINIO_BROWSER_REDIRECT_URL=http://s3console.${BASEURL}"
      - "MINIO_DOMAIN=http://s3.${BASEURL}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.routers.minio.rule=Host(`s3.${BASEURL}`)"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.routers.minio-console.rule=Host(`s3console.l${BASEURL}`)"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"

  hmq:
    build:
      context: "server"
    ports:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hmq.rule=Host(`hmq.${BASEURL}`)"
      - "traefik.http.routers.hmq.entrypoints=web"
    environment:
      - "MONGODB_CONNSTR=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo/hq"
      - "API_SALT=${API_SALT}"
      - "API_ADMINTOKEN=${API_ADMINTOKEN}"

