version: "3.3"

services:
  hmq:
    volumes:
      - "./server/app/:/code/app/"
  mongo:
    volumes:
     - "prod-mongodb:/data/db"
  minio:
    volumes:
      - "prod-minio:/data"

volumes:
  prod-minio:
    external: True
  prod-mongodb:
    external: True
