version: "3.3"

services:
  traefik:
    image: "traefik:v2.8"
    restart: "unless-stopped"
    command:
      # docker
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # API
      - "--api=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./SSLcertificates:/SSLcertificates"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # Expose container
      - "traefik.enable=true"

      # HTTP
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${BASEURL}`)"
      - "traefik.http.middlewares.upgradeHTTP.redirectscheme.scheme=https"
      - "traefik.http.middlewares.upgradeHTTP.redirectscheme.permanent=true"
      - "traefik.http.routers.traefik.middlewares=upgradeHTTP"

      # HTTPS
      - "traefik.http.routers.traefiksecure.entrypoints=websecure"
      - "traefik.http.routers.traefiksecure.rule=Host(`traefik.${BASEURL}`)"
      - "traefik.http.routers.traefiksecure.tls=true"
      - "traefik.http.routers.traefiksecure.service=api@internal"
      - "traefik.http.routers.traefiksecure.middlewares=auth"

      # Authentication
      - "traefik.http.middlewares.auth.basicauth.users=admin:${TRAEFIK_ADMIN_PASS}"
  redis:
    image: "redis:latest"
    restart: "unless-stopped"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.service=redis"
      - "traefik.tcp.routers.redis.rule=HostSNI(`redis.${BASEURL}`)"
      - "traefik.tcp.routers.redis.tls=true"
      - "traefik.tcp.routers.redis.tls.certresolver=lets-encrypt"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"
      - "traefik.tcp.routers.redis.entrypoints=websecure"

  mongo:
    image: "mongo:5.0"
    restart: "unless-stopped"
    ports:
     - "27017:27017"
    environment:
     - "MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}"
     - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}"

  minio:
    image: "minio/minio:RELEASE.2022-01-08T03-11-54Z"
    restart: "unless-stopped"
    command: "server /data --console-address :9001 --address :9000"
    expose:
      - 9000
      - 9001
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASS}"
      - "MINIO_BROWSER_REDIRECT_URL=http://s3console.${BASEURL}"
      - "MINIO_DOMAIN=http://s3.${BASEURL}"
    labels:
      # general
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # MinIO
      - "traefik.http.routers.miniosecure.entrypoints=websecure"  
      - "traefik.http.routers.miniosecure.service=minio"
      - "traefik.http.routers.miniosecure.rule=Host(`s3.${BASEURL}`)"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

      # MinIO console
      - "traefik.http.routers.minio-consolesecure.entrypoints=websecure"  
      - "traefik.http.routers.minio-consolesecure.service=minio-console"
      - "traefik.http.routers.minio-consolesecure.rule=Host(`s3console.${BASEURL}`)"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"

      # HTTPS
      - "traefik.http.routers.minio-consolesecure.tls=true"
      - "traefik.http.routers.miniosecure.tls=true"
  hmq:
    build:
      context: "server"
    ports:
      - "80"
    labels:
      # genereal
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # HMQ
      - "traefik.http.routers.hmqsecure.rule=Host(`hmq.${BASEURL}`)"
      - "traefik.http.routers.hmqsecure.entrypoints=websecure"

      # HTTP 
      - "traefik.http.routers.hmq.entrypoints=web"
      - "traefik.http.routers.hmq.rule=Host(`hmq.${BASEURL}`)"
      - "traefik.http.middlewares.upgradeHTTP.redirectscheme.scheme=https"
      - "traefik.http.middlewares.upgradeHTTP.redirectscheme.permanent=true"
      - "traefik.http.routers.hmq.middlewares=upgradeHTTP"
      
      # HTTPS
      - "traefik.http.routers.hmqsecure.tls=true"
      
    environment:
      - "MONGODB_CONNSTR=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo/hq"
      - "API_SALT=${API_SALT}"
      - "API_ADMINTOKEN=${API_ADMINTOKEN}"

