services:
  traefik:
    image: "traefik:v3.3.2"
    restart: "unless-stopped"
    command:
      # docker
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # API
      - "--api=true"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./SSLcertificates:/SSLcertificates"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # Expose container
      - "traefik.enable=true"

      # HTTP
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${BASEURL}`)"
      - "traefik.http.middlewares.upgradeHTTP.redirectscheme.scheme=https"
      - "traefik.http.middlewares.upgradeHTTP.redirectscheme.permanent=true"
      - "traefik.http.routers.traefik.middlewares=upgradeHTTP"

      # HTTPS
      - "traefik.http.routers.traefiksecure.entrypoints=websecure"
      - "traefik.http.routers.traefiksecure.rule=Host(`traefik.${BASEURL}`)"
      - "traefik.http.routers.traefiksecure.tls=true"
      - "traefik.http.routers.traefiksecure.service=api@internal"
      - "traefik.http.routers.traefiksecure.middlewares=auth"

      # Authentication
      - "traefik.http.middlewares.auth.basicauth.users=admin:${TRAEFIK_ADMIN_PASS}"
  mongo:
    image: "mongo:5.0"
    restart: "unless-stopped"
    ports:
     - "27017:27017"
    environment:
     - "MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}"
     - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}"
  hmq:
    build:
      context: "server"
    restart: "unless-stopped"
    ports:
      - "80"
    labels:
      # genereal
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # HMQ
      - "traefik.http.routers.hmqsecure.rule=Host(`hmq.${BASEURL}`)"
      - "traefik.http.routers.hmqsecure.entrypoints=websecure"

      # HTTP 
      - "traefik.http.routers.hmq.entrypoints=web"
      - "traefik.http.routers.hmq.rule=Host(`hmq.${BASEURL}`)"
      - "traefik.http.middlewares.upgradeHTTP.redirectscheme.scheme=https"
      - "traefik.http.middlewares.upgradeHTTP.redirectscheme.permanent=true"
      - "traefik.http.routers.hmq.middlewares=upgradeHTTP"
      
      # HTTPS
      - "traefik.http.routers.hmqsecure.tls=true"
      
    environment:
      - "MONGODB_CONNSTR=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@mongo/hq"
      - "ADMIN_SIGN=${ADMIN_SIGN}"

  dash:
    build:
      context: "dashboard"
    restart: "unless-stopped"
    ports:
      - "80"
    labels:
      # genereal
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Dashboard
      - "traefik.http.routers.dashsecure.rule=Host(`queue.${BASEURL}`)"
      - "traefik.http.routers.dashsecure.entrypoints=websecure"
        # - "traefik.http.routers.dashsecure.loadbalancer.server.port=8501"

      # HTTP 
      - "traefik.http.routers.dash.entrypoints=web"
      - "traefik.http.routers.dash.rule=Host(`queue.${BASEURL}`)"
      - "traefik.http.middlewares.upgradeHTTP.redirectscheme.scheme=https"
      - "traefik.http.middlewares.upgradeHTTP.redirectscheme.permanent=true"
      - "traefik.http.routers.dash.middlewares=upgradeHTTP"
      
      # HTTPS
      - "traefik.http.routers.dashsecure.tls=true"
      
