name: tests
on: push
jobs:
        test:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Build the stack
                          run: |
                                cd src/
                                docker volume create dev-mongodb
                                docker volume create dev-minio
                                docker-compose -f docker-compose.yml -f docker-compose.dev.yml -p dev --env-file env.dev.yml up --build -d
                        - name: Test Server
                          run: |
                                docker exec dev_api_1 pytest --cov=./ --cov-report xml:coverage.xml
                                docker cp dev_api_1:/code/coverage.xml src/server/coverage.xml
                        - name: Test User
                          run: |
                                docker build -t dev-user user
                                docker run -d --network="host" --name devuser dev-user sleep 10000
                                docker exec devuser pytest --cov=./ --cov-report xml:coverage.xml
                                docker cp devuser:/code/hmq/coverage.xml src/user/hmq/coverage.xml
                                docker stop devuser
                        - uses: codecov/codecov-action@v3
                          with:
                                token: ${{ secrets.CODECOV_TOKEN }}
                                files: src/user/hmq/coverage.xml,src/server/coverage.xml
                                fail_ci_if_error: true
                                verbose: true
