name: server-test
on: push
jobs:
        test:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Build the stack
                          run: |
                                  cd src/server/
                                  docker volume create dev-mongodb
                                  docker volume create dev-minio
                                  docker-compose -f docker-compose.yml -f docker-compose.dev.yml -p dev --env-file env.dev.yml up --build -d
                        - name: Test Server
                          run: |
                                  docker exec dev_api_1 pytest --cov=./ --cov-report xml:coverage.xml
                                docker cp dev_api_1:/code/coverage.xml src/server/api/coverage.xml
                        - name: Set up Python 3.10
                          uses: actions/setup-python@v4
                          with:
                                python-version: "3.10"
                        - name: Install dependencies
                          run: |
                                python -m pip install --upgrade pip
                                pip install -r src/user/requirements.txt
                        - name: Test User
                          run: |
                                cd src/user/hq
                                pytest --cov=./ --cov-report xml:coverage.xml
                                cd ../../../
                        - uses: codecov/codecov-action@v3
                          with:
                                token: ${{ secrets.CODECOV_TOKEN }}
                                files: src/user/hq/coverage.xml,src/server/api/coverage.xml
                                fail_ci_if_error: true
                                verbose: true
